version: "3.8"

services:
  db:
    image: postgres:13
    platform: linux/arm64/v8
    container_name: odoo-db
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./odoo/db-data:/var/lib/postgresql/data
    networks:
      - woodoo-net

  odoo:
    image: odoo:14
    platform: linux/amd64  # Odoo image NEM natív ARM64, így emuláció kell
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - ./odoo/extra-addons:/mnt/extra-addons
    networks:
      - woodoo-net

  wp-db:
    image: mariadb:10.5
    platform: linux/arm64/v8
    container_name: wp-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./wordpress/db-data:/var/lib/mysql
    networks:
      - woodoo-net

  wordpress:
    image: wordpress:latest
    platform: linux/arm64/v8
    container_name: wordpress
    depends_on:
      - wp-db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: wp-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wordpress/html:/var/www/html
    networks:
      - woodoo-net

  nginx:
    image: nginx:latest
    platform: linux/arm64/v8
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - odoo
      - wordpress
    networks:
      - woodoo-net

volumes:
  # Ezek a volume-ok fizikailag a projekten belül lesznek
  # de ha külön docker volume-ot akarsz, csak írd át őket sima nevekre
  odoo-db-data:
  wp-db-data:

networks:
  woodoo-net:
    driver: bridge