version: '3.8'

services:
  odoo:
    build: ./odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - woodoo-net

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - woodoo-net

  wordpress:
    build: ./wordpress
    depends_on:
      - wp-db
    environment:
      - WORDPRESS_DB_HOST=wp-db
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    networks:
      - woodoo-net

  wp-db:
    image: mariadb:10.5
    platform: linux/arm64/v8
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - wp-db-data:/var/lib/mysql
    networks:
      - woodoo-net

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - odoo
      - wordpress
    networks:
      - woodoo-net

volumes:
  odoo-db-data:
  wp-db-data:

networks:
  woodoo-net:
    driver: bridge