services:
  odoo:
    image: ghcr.io/castlecraft/odoo14-arm:latest
    platform: linux/arm64
    depends_on:
      - odoo-db
    environment:
      - HOST=${ODOO_DB_HOST}
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/addons:/mnt/extra-addons
    networks:
      - woodoo-net

  odoo-db:
    image: postgres:13
    platform: linux/arm64
    environment:
      - POSTGRES_DB=${ODOO_DB_NAME}
      - POSTGRES_USER=${ODOO_DB_USER}
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - woodoo-net

  wordpress:
    image: arm64v8/wordpress:latest
    platform: linux/arm64
    depends_on:
      - wp-db
    environment:
      - WORDPRESS_DB_HOST=wp-db
      - WORDPRESS_DB_NAME=${WP_DB_NAME}
      - WORDPRESS_DB_USER=${WP_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WP_DB_PASSWORD}
    ports:
      - "8080:80"
    volumes:
      - ./wordpress/html:/var/www/html
    networks:
      - woodoo-net

  wp-db:
    image: arm64v8/mariadb:10.5
    platform: linux/arm64
    environment:
      - MYSQL_DATABASE=${WP_DB_NAME}
      - MYSQL_USER=${WP_DB_USER}
      - MYSQL_PASSWORD=${WP_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${WP_DB_ROOT_PASSWORD}
    volumes:
      - wp-db-data:/var/lib/mysql
    networks:
      - woodoo-net

  nginx:
    image: nginx:alpine
    platform: linux/arm64
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    depends_on:
      - odoo
      - wordpress
    networks:
      - woodoo-net

volumes:
  odoo-db-data:
  wp-db-data:

networks:
  woodoo-net: