services:
  odoo-db:
    image: postgres:13
    platform: linux/arm64
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - woodoo-net

  odoo:
    build:
      context: ./odoo
      dockerfile: Dockerfile
      platform: linux/arm64
    depends_on:
      - odoo-db
    environment:
      - HOST=${ODOO_DB_HOST}
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/addons:/mnt/extra-addons
    networks:
      - woodoo-net

  wp-db:
    image: mariadb:10.5
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - wp-db-data:/var/lib/mysql
    networks:
      - woodoo-net

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
      platform: linux/arm64
    depends_on:
      - wp-db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - woodoo-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
    depends_on:
      - wordpress
      - odoo
    networks:
      - woodoo-net

volumes:
  odoo-db-data:
  wp-db-data:
  wordpress-data:

networks:
  woodoo-net:
    driver: bridge