version: '3.8'
services:
  odoo_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    networks:
      - erp_network

  odoo:
    image: odoo:14.0
    platform: linux/amd64
    depends_on:
      - odoo_db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
    environment:
      - HOST=odoo_db
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - erp_network

volumes:
  odoo_db_data:
networks:
  erp_network:
