version: '3.1'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: K775bZ~/@08P
      MYSQL_DATABASE: WooDoo
      MYSQL_USER: f020woodoo
      MYSQL_PASSWORD: K775bZ~/@08P-database

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: f020woodoo
      WORDPRESS_DB_PASSWORD: K775bZ~/@08P-database
      WORDPRESS_DB_NAME: WooDoo
